### ISSUE TITLE
modules with @scope end up in dependency load failure

### ISSUE THREAD

**Issue by freakadunse** [ui5-community/babel-plugin-transform-modules-ui5#61]
hey there!

i am using the plugin to transform my typescript code to ui5 which works pretty well.
But i have one issue:

We're hosting a onPremise git for the npm registry, which works with @scopes. 
So my package is @scope/package-name.

As soon as i import the package and try to run the page, i'll get the following error:

`The following error occurred while displaying routing target with name 'Overview': ModuleError: Failed to resolve dependencies of '<Application>/controller/Overview.controller.js'
 -> '@<scope>/<module>.js': failed to load '@<scope>/<module>.js' from https://sapui5.hana.ondemand.com/resources/@<scope>/<module>.js: script load error -`
For sure, my package does not exist in the sapui5 hana ondemand resources :-)

The generated define also includes the non existing module:
`sap.ui.define(["../model/Formatter", "./BaseController.controller", "@<scope>/<module>", "sap/ui/core/mvc/Controller"], function (__Formatter, __BaseController, __Validator, Controller) {`

Any idea how to get this working again with @scope-modules?

Thanks!

BR
Pascal

**Comment by petermuessig** [comment]
Hi @freakadunse ,

normally all unknown resource paths are loaded relative to the UI5 bootstrap URL. The scope is just seen as a namespace and the dependency isn't being resolved at all with the babel plugin. This needs to be handled either by the UI5 runtime or by the UI5 tooling.

In the meantime, a UI5 tooling extension is handling the inclusion of third-party/OSS components from NPM packages. When using the UI5 tooling you can add the `ui5-tooling-modules` and include those NPM packages into your project. With the option `addToNamespace` you even get application local dependencies. 

For more details check out the [`ui5-tooling-modules`](https://github.com/ui5-community/ui5-ecosystem-showcase/tree/main/packages/ui5-tooling-modules).

Closing this issue, as this isn't related to the babel plugin.

Cheers, Peter
